stages:
  - build
  - test

image: edbizarro/gitlab-ci-pipeline-php:7.1-alpine

#### Build
# We need to build development dependencies as they are needed to testing
composer:
  stage: build
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
  artifacts:
    expire_in: 1 week
    paths:
      - vendor/
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/
      - ~/.composer/cache/files
  only:
    - develop
    - master

#### Test
phpunit:
  stage: test
  dependencies:
    - composer
  script:
    - ./vendor/phpunit/phpunit/phpunit -v --coverage-text --stderr
  only:
    - develop
    - master

codestyle:
  stage: test
  dependencies:
    - composer
  script:
    - ./vendor/bin/phpcs --colors
  only:
    - develop
    - master
